name: Daily

on:
  schedule:
    - cron: '15 15 * * *' # UTC

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          # See https://github.com/docker/build-push-action/issues/654#issuecomment-1285190151
          config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (docker.io/mirakc/timeshift-gerbera)
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./gerbera
          tags: |
            mirakc/timeshift-gerbera:main
          build-args: |
            prefix=main-
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
      - name: Build and push (docker.io/mirakc/timeshift-samba)
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./samba
          tags: |
            mirakc/timeshift-samba:main
          build-args: |
            prefix=main-
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
