name: weekly

on:
  schedule:
    - cron: '21 21 * * 5'  # every Friday
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          # See https://github.com/docker/build-push-action/issues/654#issuecomment-1285190151
          config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Get the latest version of mirakc/timeshift-fs:alpine
        id: latest-version
        run: |
          IMAGE='mirakc/timeshift-fs:alpine'
          ENTRYPOINT=/usr/local/bin/mirakc-timeshift-fs
          VERSION=$(docker run --rm --entrypoint=$ENTRYPOINT $IMAGE --version | cut -d' ' -f2)
          echo "Version: $VERSION"
          echo "version=$VERSION" >>$GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (mirakc/timeshift-gerbera)
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./gerbera
          tags: |
            docker.io/mirakc/timeshift-gerbera
            docker.io/mirakc/timeshift-gerbera:${{ steps.latest-version.outputs.version }}
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
      - name: Build and push (mirakc/timeshift-samba)
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./samba
          tags: |
            docker.io/mirakc/timeshift-samba
            docker.io/mirakc/timeshift-samba:${{ steps.latest-version.outputs.version }}
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
